<a href="https://colab.research.google.com/github/shahbazmaryam25/Data-Science-and-Generative-AI/blob/main/week_3_2_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np

# create a dictionary of orders
orders = {'o10001':{'date':'2024/01/10', 'product':'Hoodie', 'quantity':'1'},
            'o10002':{'date':'2024/01/13', 'product':'Tote bag', 'quantity':'2'},
            'o10003':{'date':'2024/01/14', 'product':'Pencil', 'quantity':'10'},
            'o10004':{'date':'2024/01/15', 'product':'T-shirt', 'quantity':'2'}
}

# convert to a dataframe
orders_df = pd.DataFrame(orders)

# create a dicitonary of products
products = {'123':{'name':'Hoodie', 'cost_price':12.12, 'sale_price':15.00},
            '124':{'name':'Tote bag', 'cost_price':2.15, 'sale_price':9.99},
            '125':{'name':'Pencil', 'cost_price':22.45, 'sale_price':49.99},
            '126':{'name':'T-shirt', 'cost_price':0.45, 'sale_price':2.99},
            '127':{'name':'Honours degree', 'cost_price':0.78, 'sale_price':1.49}
}

# convert to a dataframe
products_df = pd.DataFrame(products)

# transpose (flip on their axes) both dataframes
orders_df = orders_df.transpose()
products_df = products_df.transpose()

# join (left) orders_df and products_df
joined_df = orders_df.merge(products_df, how='left', left_on='product', right_on='name')

# drop the repeated column and display on screen
joined_df = joined_df.drop(['name'], axis=1)
joined_df

         date   product quantity cost_price sale_price
0  2024/01/10    Hoodie        1      12.12       15.0
1  2024/01/13  Tote bag        2       2.15       9.99
2  2024/01/14    Pencil       10      22.45      49.99
3  2024/01/15   T-shirt        2       0.45       2.99

In [17]:
joined_df['quantity'] = pd.to_numeric(joined_df['quantity'])
joined_df['total_cost_price'] = joined_df['quantity'] * joined_df['cost_price']
joined_df['total_sale_price'] = joined_df['quantity'] * joined_df['sale_price']
joined_df

,date,product,quantity,cost_price,sale_price,total_cost_price,total_sale_price
0,2024/01/10,Hoodie,1,12.12,15.0,12.12,15.0
1,2024/01/13,Tote bag,2,2.15,9.99,4.3,19.98
2,2024/01/14,Pencil,10,22.45,49.99,224.5,499.9
3,2024/01/15,T-shirt,2,0.45,2.99,0.9,5.98

In [18]:
print(joined_df.dtypes)

date                object
product             object
quantity             int64
cost_price          object
sale_price          object
total_cost_price    object
total_sale_price    object
dtype: object

In [19]:
field_list = ['quantity', 'cost_price', 'sale_price']
for field in field_list:
    joined_df[field] = joined_df[field].astype(float)

In [20]:
joined_df['total_cost_price'] = joined_df['quantity'] * joined_df['cost_price']
joined_df['total_sale_price'] = joined_df['quantity'] * joined_df['sale_price']
joined_df

,date,product,quantity,cost_price,sale_price,total_cost_price,total_sale_price
0,2024/01/10,Hoodie,1.0,12.12,15.00,12.12,15.00
1,2024/01/13,Tote bag,2.0,2.15,9.99,4.30,19.98
2,2024/01/14,Pencil,10.0,22.45,49.99,224.50,499.90
3,2024/01/15,T-shirt,2.0,0.45,2.99,0.90,5.98

In [21]:
joined_df.iloc[0]

date                2024/01/10
product                 Hoodie
quantity                   1.0
cost_price               12.12
sale_price                15.0
total_cost_price         12.12
total_sale_price          15.0
Name: 0, dtype: object

In [22]:
joined_df.iloc[0:2]

,date,product,quantity,cost_price,sale_price,total_cost_price,total_sale_price
0,2024/01/10,Hoodie,1.0,12.12,15.00,12.12,15.00
1,2024/01/13,Tote bag,2.0,2.15,9.99,4.30,19.98

In [23]:
joined_df['product']

0      Hoodie
1    Tote bag
2      Pencil
3     T-shirt
Name: product, dtype: object

In [24]:
df_subset_one = joined_df.iloc[0:2]
df_subset_one

,date,product,quantity,cost_price,sale_price,total_cost_price,total_sale_price
0,2024/01/10,Hoodie,1.0,12.12,15.00,12.12,15.00
1,2024/01/13,Tote bag,2.0,2.15,9.99,4.30,19.98

In [25]:
df_subset_two = joined_df[['product', 'quantity', 'total_sale_price']]
df_subset_two

    product  quantity  total_sale_price
0    Hoodie       1.0             15.00
1  Tote bag       2.0             19.98
2    Pencil      10.0            499.90
3   T-shirt       2.0              5.98

In [26]:
joined_df.to_csv('Joined_Dataframe.csv', sep=",")

 Create a calculated field for the amount of markup associated with each product? The formula for this should be: markup = (sale price - cost price) / cost price

In [27]:
products_df['markup'] = (
    products_df['sale_price'] - products_df['cost_price']
) / products_df['cost_price']

products_df

               name cost_price sale_price    markup
123          Hoodie      12.12       15.0  0.237624
124        Tote bag       2.15       9.99  3.646512
125          Pencil      22.45      49.99  1.226726
126         T-shirt       0.45       2.99  5.644444
127  Honours degree       0.78       1.49  0.910256

Create a subset of the dataframe where the total sale price is less than £20.00?

In [28]:
joined_df['total_sale_price'] = (
    joined_df['sale_price'] * joined_df['quantity'].astype(int)
)

under_20 = joined_df[
    joined_df['total_sale_price'] < 20.00
]

under_20

,date,product,quantity,cost_price,sale_price,total_cost_price,total_sale_price
0,2024/01/10,Hoodie,1.0,12.12,15.00,12.12,15.00
1,2024/01/13,Tote bag,2.0,2.15,9.99,4.30,19.98
3,2024/01/15,T-shirt,2.0,0.45,2.99,0.90,5.98