<a href="https://colab.research.google.com/github/shahbazmaryam25/Data-Science-and-Generative-AI/blob/main/week_3_2_04_fake_sales_xlsx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
upload = files.upload()

Saving fake_sales.xlsx to fake_sales.xlsx

In [2]:
import pandas as pd # if not already done in your session
import numpy as np

jan_df = pd.read_excel('fake_sales.xlsx', sheet_name='January')
jan_df

         Date  US_Sales  UK_Sales  Canada_Sales
0  2024-01-01   9300.52   4270.45       8330.70
1  2024-01-02   6250.65   5680.58       3650.58
2  2024-01-03   6870.29   8380.25       1900.04
3  2024-01-04   5620.17   9420.67       7260.93
4  2024-01-05   9430.28   8640.58       8180.83
5  2024-01-06   9920.03   2150.91       5900.60
6  2024-01-07   7340.07   3810.27       7500.20
7  2024-01-08   3050.27   2060.32       2760.60
8  2024-01-09   6570.98   3270.48       1020.84
9  2024-01-10   1970.04   4520.89       3920.62
10 2024-01-11   1910.55   2720.27       5400.94
11 2024-01-12   3110.73   3060.77       1250.16
12 2024-01-13   5620.41   5750.40       8130.10
13 2024-01-14   8560.79   5250.90       5480.12
14 2024-01-15   2150.69   7230.77       3210.70
15 2024-01-16   4820.49   3320.96       9530.08
16 2024-01-17   5760.01   4320.24       6470.91
17 2024-01-18   8490.52   6300.55       4190.33
18 2024-01-19   8950.99   7630.46       1750.46
19 2024-01-20   6180.84   1320.65           NaN
20 2024-01-21   6400.64   4410.63       1000.69
21 2024-01-22   5290.64   2140.94       4320.04
22 2024-01-23   1320.28   8400.19       6800.29
23 2024-01-24   7640.50       NaN       4530.88
24 2024-01-25   1130.03   2450.94       3890.31
25 2024-01-26   1480.84   2950.27       5690.83
26 2024-01-27   3120.95   9970.59       7720.27
27 2024-01-28   6300.24   5720.05       5810.64
28 2024-01-29   7950.42   9230.52       2850.63
29 2024-01-30   7020.59   5130.04       2130.45
30 2024-01-31   7530.65   8620.11       6140.37

In [3]:
jan_df.head()

        Date  US_Sales  UK_Sales  Canada_Sales
0 2024-01-01   9300.52   4270.45       8330.70
1 2024-01-02   6250.65   5680.58       3650.58
2 2024-01-03   6870.29   8380.25       1900.04
3 2024-01-04   5620.17   9420.67       7260.93
4 2024-01-05   9430.28   8640.58       8180.83

In [5]:
print(jan_df.dtypes)

Date            datetime64[ns]
US_Sales               float64
UK_Sales               float64
Canada_Sales           float64
dtype: object

In [6]:
feb_df = pd.read_excel('fake_sales.xlsx', sheet_name='February')
feb_df.head()

        Date  US Sales  UK Sales  Canada Sales
0 2024-02-01   8470.48   5170.39       3710.78
1 2024-02-02   4930.76   3320.80       5800.50
2 2024-02-03   6040.84   7310.09       2490.01
3 2024-02-04   6840.61   8980.43       4040.51
4 2024-02-05   4070.03   6360.77           NaN

In [7]:
feb_df.columns = ['Date', 'US_Sales', 'UK_Sales', 'Canada_Sales']
feb_df.head()

        Date  US_Sales  UK_Sales  Canada_Sales
0 2024-02-01   8470.48   5170.39       3710.78
1 2024-02-02   4930.76   3320.80       5800.50
2 2024-02-03   6040.84   7310.09       2490.01
3 2024-02-04   6840.61   8980.43       4040.51
4 2024-02-05   4070.03   6360.77           NaN

In [8]:
sales_df = pd.concat([jan_df, feb_df], axis=0, join='outer')
sales_df.head()

        Date  US_Sales  UK_Sales  Canada_Sales
0 2024-01-01   9300.52   4270.45       8330.70
1 2024-01-02   6250.65   5680.58       3650.58
2 2024-01-03   6870.29   8380.25       1900.04
3 2024-01-04   5620.17   9420.67       7260.93
4 2024-01-05   9430.28   8640.58       8180.83

In [9]:
sales_df.tail()

         Date  US_Sales  UK_Sales  Canada_Sales
23 2024-02-24   1160.20   8500.94       4530.35
24 2024-02-25   2560.97   7350.13       8810.55
25 2024-02-26   8590.08   7320.83       6370.43
26 2024-02-27   4850.27   4870.57       6460.61
27 2024-02-28   8690.32   2350.45       5110.09

In [10]:
sales_df.isnull().sum()

Date            0
US_Sales        1
UK_Sales        1
Canada_Sales    2
dtype: int64

In [11]:
sales_df = sales_df.fillna(0)
sales_df.isnull().sum()

Date            0
US_Sales        0
UK_Sales        0
Canada_Sales    0
dtype: int64

In [12]:
sales_df['US_Sales'] = sales_df['US_Sales'] * 0.76
sales_df['Canada_Sales'] = sales_df['Canada_Sales'] * 0.56

In [13]:
sales_df['Month'] = pd.DatetimeIndex(sales_df['Date']).month
sales_df.head()

        Date   US_Sales  UK_Sales  Canada_Sales  Month
0 2024-01-01  7068.3952   4270.45     4665.1920      1
1 2024-01-02  4750.4940   5680.58     2044.3248      1
2 2024-01-03  5221.4204   8380.25     1064.0224      1
3 2024-01-04  4271.3292   9420.67     4066.1208      1
4 2024-01-05  7167.0128   8640.58     4581.2648      1

In [14]:
sales_df.tail()

         Date   US_Sales  UK_Sales  Canada_Sales  Month
23 2024-02-24   881.7520   8500.94     2536.9960      2
24 2024-02-25  1946.3372   7350.13     4933.9080      2
25 2024-02-26  6528.4608   7320.83     3567.4408      2
26 2024-02-27  3686.2052   4870.57     3617.9416      2
27 2024-02-28  6604.6432   2350.45     2861.6504      2

In [15]:
sales_df['Month'] = np.where(sales_df.Month == 1, 'Jan', 'Feb')
sales_df.head()

        Date   US_Sales  UK_Sales  Canada_Sales Month
0 2024-01-01  7068.3952   4270.45     4665.1920   Jan
1 2024-01-02  4750.4940   5680.58     2044.3248   Jan
2 2024-01-03  5221.4204   8380.25     1064.0224   Jan
3 2024-01-04  4271.3292   9420.67     4066.1208   Jan
4 2024-01-05  7167.0128   8640.58     4581.2648   Jan

In [16]:
sales_df.tail()

         Date   US_Sales  UK_Sales  Canada_Sales Month
23 2024-02-24   881.7520   8500.94     2536.9960   Feb
24 2024-02-25  1946.3372   7350.13     4933.9080   Feb
25 2024-02-26  6528.4608   7320.83     3567.4408   Feb
26 2024-02-27  3686.2052   4870.57     3617.9416   Feb
27 2024-02-28  6604.6432   2350.45     2861.6504   Feb

In [17]:
sales_group_df = sales_df.groupby(['Month']).mean()
sales_group_df

                     Date     US_Sales     UK_Sales  Canada_Sales
Month
Feb   2024-02-14 12:00:00  4022.115157  5219.794286   3018.013400
Jan   2024-01-16 00:00:00  4340.950839  5101.150000   2650.518658

Change the mean to a median

In [18]:
sales_group_median_df = sales_df.groupby(['Month']).median(numeric_only=True)

sales_group_median_df

        US_Sales  UK_Sales  Canada_Sales
Month
Feb    3815.7624   5080.54     3183.8604
Jan    4750.4940   4520.89     2537.2928

What difference does this make to the result? Would this be expected?

Using the median instead of the mean gives the middle daily sales value for each month rather than the average. In January, US sales have a higher median (£4,750.49) than in February (£3,815.76), whereas UK sales have a higher median in February (£5,080.54) than in January (£4,520.89). Canada also has higher median sales in February (£3,183.86) than in January (£2,537.29).

These differences are expected because the median is less affected by unusually high or low sales figures than the mean. Comparing the two helps show whether extreme values may be influencing the average.

In [19]:

df = pd.DataFrame({"Team": ["DS", "DT", "DT", "DS", "DS"], "salary": [100000, 100, 20000, 0, 100000]})
print("Raw Data")
print(df)
print("\n")

# team based aggregation (average)
# reset index means we convert the output to a flat 2D shape rather than leaving a gap
mean_df = df.groupby(['Team']).mean().reset_index()

print("Aggregation by Mean")
print(mean_df)
print("\n")

# team based aggregation (sum)
sum_df = df.groupby(['Team']).sum().reset_index()

print("Aggregation by Sum")
print(sum_df)
print("\n")

# team based aggregation (median)
median_df = df.groupby(['Team']).median().reset_index()

print("Aggregation by Median")
print(median_df)
print("\n")

# team based aggregation (maximum)
max_df = df.groupby(['Team']).max().reset_index()

print("Aggregation by Maximum")
print(max_df)
print("\n")

Raw Data
  Team  salary
0   DS  100000
1   DT     100
2   DT   20000
3   DS       0
4   DS  100000


Aggregation by Mean
  Team        salary
0   DS  66666.666667
1   DT  10050.000000


Aggregation by Sum
  Team  salary
0   DS  200000
1   DT   20100


Aggregation by Median
  Team    salary
0   DS  100000.0
1   DT   10050.0


Aggregation by Maximum
  Team  salary
0   DS  100000
1   DT   20000

In [20]:
df = pd.DataFrame({"id": [3, 1, 2, 4, 10], "salary": [100000, 100, 20000, 0, 100000],
                   "dob": ["10/01/1950", "01/01/1990", "01/01/1980", "12/12/1981", "13/06/1981"]})
print(df)

# convert a column which has a date stored as string, into a column
# stored as date. dayfirst=True means we use the UK style of date
# (DDMMYYYY) rather than US (MMDDYYYY)
df['dob'] = pd.to_datetime(df['dob'], dayfirst=True)

# from a date object create cols for year, month, day, hour and minute
df['Year'] =  pd.DatetimeIndex(df['dob']).year
df['Month'] = pd.DatetimeIndex(df['dob']).month
df['Day'] = pd.DatetimeIndex(df['dob']).day
df['Hour'] = pd.DatetimeIndex(df['dob']).hour
df['Minute'] = pd.DatetimeIndex(df['dob']).minute

print("\n")
print(df)

# work out age by substracting the DOB from the date today
# note this is much harder than you may think it would be because years
# are different lengths and so ambiguous
df["Age"] = pd.to_datetime("today", dayfirst=True)-df['dob']
df["Age"] = round(df.Age.dt.days / 365, 1)

print("\n")
print(df)

   id  salary         dob
0   3  100000  10/01/1950
1   1     100  01/01/1990
2   2   20000  01/01/1980
3   4       0  12/12/1981
4  10  100000  13/06/1981


   id  salary        dob  Year  Month  Day  Hour  Minute
0   3  100000 1950-01-10  1950      1   10     0       0
1   1     100 1990-01-01  1990      1    1     0       0
2   2   20000 1980-01-01  1980      1    1     0       0
3   4       0 1981-12-12  1981     12   12     0       0
4  10  100000 1981-06-13  1981      6   13     0       0


   id  salary        dob  Year  Month  Day  Hour  Minute   Age
0   3  100000 1950-01-10  1950      1   10     0       0  76.8
1   1     100 1990-01-01  1990      1    1     0       0  36.8
2   2   20000 1980-01-01  1980      1    1     0       0  46.9
3   4       0 1981-12-12  1981     12   12     0       0  44.9
4  10  100000 1981-06-13  1981      6   13     0       0  45.4

In [21]:
df = pd.DataFrame({"student": [1, 2, 3, 4, 5],
                   "deadline": ["01/11/2025", "02/11/2025", "03/11/2025", "04/11/2025", "05/11/2025"],
                   "submission": ["01/11/2025", "01/11/2025", "02/12/2025", "03/11/2025", "01/12/2025"]})

df.head()

   student    deadline  submission
0        1  01/11/2025  01/11/2025
1        2  02/11/2025  01/11/2025
2        3  03/11/2025  02/12/2025
3        4  04/11/2025  03/11/2025
4        5  05/11/2025  01/12/2025

In [22]:
# convert a column which has a date stored as string, into a column
# stored as date. dayfirst=True means we use the UK style of date
# (DDMMYYYY) rather than US (MMDDYYYY)
# but this time inside a for loop

date_cols = ["deadline", "submission"]

for col in date_cols:
  df[col] = pd.to_datetime(df[col], dayfirst=True)

df.head()

   student   deadline submission
0        1 2025-11-01 2025-11-01
1        2 2025-11-02 2025-11-01
2        3 2025-11-03 2025-12-02
3        4 2025-11-04 2025-11-03
4        5 2025-11-05 2025-12-01

In [23]:
df["after_deadline"] = df["submission"] - df["deadline"]
df.head()

   student   deadline submission after_deadline
0        1 2025-11-01 2025-11-01         0 days
1        2 2025-11-02 2025-11-01        -1 days
2        3 2025-11-03 2025-12-02        29 days
3        4 2025-11-04 2025-11-03        -1 days
4        5 2025-11-05 2025-12-01        26 days