<a href="https://colab.research.google.com/github/shahbazmaryam25/Data-Science-and-Generative-AI/blob/main/week_3_2_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np

orders = {'o10001':{'date':'2024/01/10', 'product':'Hoodie', 'quantity':'1'},
            'o10002':{'date':'2024/01/13', 'product':'Tote bag', 'quantity':'2'},
            'o10003':{'date':'2024/01/14', 'product':'Pencil', 'quantity':'10'},
            'o10004':{'date':'2024/01/15', 'product':'T-shirt', 'quantity':'2'}
}

orders_df = pd.DataFrame(orders)
orders_df

              o10001      o10002      o10003      o10004
date      2024/01/10  2024/01/13  2024/01/14  2024/01/15
product       Hoodie    Tote bag      Pencil     T-shirt
quantity           1           2          10           2

In [22]:
products = {'123':{'name':'Hoodie', 'cost_price':12.12, 'sale_price':15.00},
            '124':{'name':'Tote bag', 'cost_price':2.15, 'sale_price':9.99},
            '125':{'name':'Pencil', 'cost_price':22.45, 'sale_price':49.99},
            '126':{'name':'T-shirt', 'cost_price':0.45, 'sale_price':2.99},
            '127':{'name':'Honours degree', 'cost_price':0.78, 'sale_price':1.49}
}

products_df = pd.DataFrame(products)
products_df

               123       124     125      126             127
name        Hoodie  Tote bag  Pencil  T-shirt  Honours degree
cost_price   12.12      2.15   22.45     0.45            0.78
sale_price    15.0      9.99   49.99     2.99            1.49

In [23]:
orders_df = orders_df.transpose()
products_df = products_df.transpose()

In [24]:
orders_df

              date   product quantity
o10001  2024/01/10    Hoodie        1
o10002  2024/01/13  Tote bag        2
o10003  2024/01/14    Pencil       10
o10004  2024/01/15   T-shirt        2

In [25]:
# Ensure the DataFrames are properly transposed so that features like 'product' and 'name' are columns
orders_df_t = orders_df.T if 'product' not in orders_df.columns else orders_df
products_df_t = products_df.T if 'name' not in products_df.columns else products_df

# Perform the merge
joined_df = orders_df_t.merge(products_df_t, how='left', left_on='product', right_on='name')
joined_df

         date   product quantity      name cost_price sale_price
0  2024/01/10    Hoodie        1    Hoodie      12.12       15.0
1  2024/01/13  Tote bag        2  Tote bag       2.15       9.99
2  2024/01/14    Pencil       10    Pencil      22.45      49.99
3  2024/01/15   T-shirt        2   T-shirt       0.45       2.99

In [26]:
joined_df = joined_df.drop(['name'], axis=1)
joined_df

         date   product quantity cost_price sale_price
0  2024/01/10    Hoodie        1      12.12       15.0
1  2024/01/13  Tote bag        2       2.15       9.99
2  2024/01/14    Pencil       10      22.45      49.99
3  2024/01/15   T-shirt        2       0.45       2.99

In [27]:
joined_df = orders_df_t.merge(
    products_df_t,
    how='left',
    left_on='product',
    right_on='name'
)

In [28]:
joined_df = orders_df_t.merge(
    products_df_t,
    how='inner',
    left_on='product',
    right_on='name'
)

joined_df

         date   product quantity      name cost_price sale_price
0  2024/01/10    Hoodie        1    Hoodie      12.12       15.0
1  2024/01/13  Tote bag        2  Tote bag       2.15       9.99
2  2024/01/14    Pencil       10    Pencil      22.45      49.99
3  2024/01/15   T-shirt        2   T-shirt       0.45       2.99

In [29]:
joined_df = orders_df_t.merge(
    products_df_t,
    how='right',
    left_on='product',
    right_on='name'
)

joined_df

         date   product quantity            name cost_price sale_price
0  2024/01/10    Hoodie        1          Hoodie      12.12       15.0
1  2024/01/13  Tote bag        2        Tote bag       2.15       9.99
2  2024/01/14    Pencil       10          Pencil      22.45      49.99
3  2024/01/15   T-shirt        2         T-shirt       0.45       2.99
4         NaN       NaN      NaN  Honours degree       0.78       1.49

In [30]:
joined_df = orders_df_t.merge(
    products_df_t,
    how='outer',
    left_on='product',
    right_on='name'
)

joined_df

         date   product quantity            name cost_price sale_price
0         NaN       NaN      NaN  Honours degree       0.78       1.49
1  2024/01/10    Hoodie        1          Hoodie      12.12       15.0
2  2024/01/14    Pencil       10          Pencil      22.45      49.99
3  2024/01/15   T-shirt        2         T-shirt       0.45       2.99
4  2024/01/13  Tote bag        2        Tote bag       2.15       9.99

.merge() combines dataframes.



how= controls the type of join.



left_on= and right_on= specify which columns to match.